INPUT:
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
  RANDOM_FLIP: "horizontal"
DATASETS:
  TRAIN: ("train",)
  TEST: ("test",)
MODEL:
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0005
  MAX_ITER: 100000
  STEPS: (20000, 40000, 60000)
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
